config/routes.rb
Basetouch::Application.routes.draw do

  resources :campaigns do
    resources :projects
  end

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  authenticated :user do
    root :to => 'campaigns#index'
  end

  root :to => 'pages#home'
  get 'about' => 'pages#about'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :name
  validates :name,  :presence => true
  belongs_to :user
  has_many :projects, :dependent => :destroy
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :launchdate, :name, :territory
  validates :name,  :presence => true
  validates :territory, :presence => true
  belongs_to :campaign
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :provider, :uid

  has_many :campaigns

	def self.from_omniauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.email = auth.info.email
	  end
	end

	def self.new_with_session(params, session)
	  if session["devise.user_attributes"]
	    new(session["devise.user_attributes"], without_protection: true) do |user|
	      user.attributes = params
	      user.valid?
	    end
	  else
	    super
	  end
	end

	def password_required?
	  super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaigns_path, notice: 'Campaign was successfully created.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end

  private
  
  def sort_column
    Campaign.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  # GET /campaigns/1/projects/1
  # GET /campaigns/1/projects/1.json
  def show
    @campaign = Campaign.find(params[:campaign_id])
    @project = @campaign.projects.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /campaigns/1/projects/new
  # GET /campaigns/1/projects/new.json
  def new
    @campaign = Campaign.find(params[:campaign_id])
    @project = @campaign.projects.new(params[:project])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /campaigns/1/projects/1/edit
  def edit
    @campaign = Campaign.find(params[:campaign_id])
    @project = @campaign.projects.find(params[:id])
  end

  # POST /campaigns/1/projects
  # POST /campaigns/1/projects.json
  def create
    @campaign = Campaign.find(params[:campaign_id])
    @project = @campaign.projects.create(params[:project])
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to campaign_path(@campaign), notice: 'Project was successfully created.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1/projects/1
  # PUT /campaigns/1/projects/1.json
  def update
    @campaign = Campaign.find(params[:campaign_id])
    @project = @campaign.projects.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to campaign_path(@campaign), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @campaign = Campaign.find(params[:campaign_id])
    @project = @campaign.projects.find(params[:id])
    @project.destroy
    
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to campaign_path(@campaign), notice: 'Project was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
	  title ||= column.titleize
	  css_class = column == sort_column ? "current #{sort_direction}" : nil
	  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
	  link_to title, {:sort => column, :direction => direction}, {:class => css_class}
	end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for(@campaign, html: { class: "form-horizontal", :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, input_html: { rows: "3" } %>
  <br />
  <%= f.button :submit, class: "btn btn-primary" %>
 
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/campaigns/index.html.erb
<h3>My Campaigns</h3>
<div class="well">
  <table class="table table-striped">
  <tr>
    <th><%= sortable "name", "Campaign Name" %></th>
    <th><%= sortable "created_at", "Start Date" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @campaigns.each do |campaign| %>
  <tr>
    <td><%= campaign.name %></td>
    <td><%= l campaign.created_at, :format => :short %></td>
    <td><%= link_to 'View', campaign %></td>
    <td><%= link_to 'Edit', edit_campaign_path(campaign) %></td>
    <td><%= link_to 'Delete', campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Campaign', new_campaign_path, :class => "btn" %>
</div>

app/views/campaigns/new.html.erb
<h1>New campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.html.erb
<h3><%= link_to 'My Campaigns', campaigns_path %> > <%= @campaign.name %></h3>
<div class="well">
  <table class="table table-striped">
  <tr>
    <th><%= sortable "name", "Project Name" %></th>
    <th><%= sortable "launchdate", "Target Launch" %></th>
    <th><%= sortable "territory", "Territory" %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @campaign.projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= l project.launchdate, :format => :short %></td>
    <td><%= project.territory %></td>
    <td><%= link_to 'View', [project.campaign, project] %></td>
    <td><%= link_to 'Edit', edit_campaign_project_path(@campaign, project) %></td>
    <td><%= link_to 'Delete', [project.campaign, project],
            :confirm => 'Are you sure?',
            :method => :delete %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'New Project', new_campaign_project_path(@campaign), :class => "btn" %>
</div>
<ul class="breadcrumb">
  <li><%= link_to 'My Campaigns', campaigns_path %><span class="divider">/</span></li>
  <li><%= @campaign.name %></li>
</ul>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "About basetouch.io", about_path %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "basetouch.io", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li> 
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
         <% end %>
        </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>basetouch.io</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
      <%= yield %>
    	<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/_user_home.html.erb
<h1>You are logged in</h1>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	About blurb will go here.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<%= render 'user_home' %>
<% else %>
	<div class="hero-unit">
		<h1>basetouch.io</h1>
		<p>
		  Taking the pain out of campaign.
		</p>
		<p>
		  <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
		</p>
	</div>
<% end %>

app/views/projects/_form.html.erb
<%= simple_form_for([@campaign, @project], html: { class: "form-horizontal", :multipart => true }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, input_html: { rows: "3" } %>
  <%= f.input :territory, :collection => ([["Domestic", "domestic"], ["International", "international"]]), input_html: { rows: "3" }  %>
  <%= f.input :launchdate, as: :datetime, input_html: { rows: "3" } %>
  <br />
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @campaign %> |
<%= link_to 'Back', campaigns_path %>

app/views/projects/show.html.erb
<h3>
	<%= link_to 'My Campaigns', campaigns_path %> > 
	<%= link_to @campaign.name, @campaign %> >
	<%= @project.name %>
</h3>
<div class="well">
  <table class="table table-striped">
  </table>
</div>